site_name: Fyq Docs
# Project information
site_name: FYQ Wiki
site_description: 一位计算机爱好者的资料整理.... 
site_author: 方毓乔
# site_url: 'https://wiki.pjmcode.top/'
strict: false

# Repository
repo_name: 'Fyq'
repo_url: 'https://github.com/123fyq123/Fyq-Wiki'

nav:
  - welcome: index.md
  - ACM:
    - 数学:
      - 组合数学:
        - 组合数: 404.md
        - 置换群:
          - polya定理: 404.md
        - 线性基: 线性基.md
        - 卡特兰数: 卡特兰数.md
        - 斯特拉数: 斯特拉数.md
      - 数论:
        - 欧拉函数: 欧拉函数.md
        - 逆元: 逆元.md
        - BSGS和扩展BSGS: BSGS.md
        - 扩展欧几里德和贝祖定理: 扩欧.md
        - 中国剩余定理: crt.md
        - 积性函数与莫比乌斯反演: 莫反.md
        - 例题: 404.md
  - PS: 
    - 基础知识入门: PS/base.md
    - 图像的基本编辑方法: PS/PS1.md
    

    

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  # favicon: img/favicon.png
  icon:
    logo: material/library

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: red
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: cyan
    accent: red
    toggle:
      icon: material/weather-night
      name: Switch to light mode

# copyright
copyright: Copyright &copy; 2022 <a href="#" target="_blank" rel="noopener noreferrer">方毓乔</a>

# extra
extra:
  search:
    language: 'jp'


# md extrc
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js