site_name: Fyq Docs
# Project information
site_name: FYQ Wiki
site_description: 一位计算机爱好者的资料整理.... 
site_author: 方毓乔
# site_url: 'https://wiki.pjmcode.top/'
strict: false

# Repository
repo_name: 'Fyq'
repo_url: 'https://github.com/123fyq123/Fyq-Wiki'

nav:
  - welcome: index.md
  - ACM:
    - 数学:
      - 组合数学:
        - 组合数: ACM/数学/组合数学/组合数.md
        - 置换群:
          - polya定理: 404.md
        - 线性基: ACM/数学/组合数学/线性基.md
        - 卡特兰数: ACM/数学/组合数学/卡特兰数.md
        - 斯特拉数: ACM/数学/组合数学/斯特拉数.md
      - 数论:
        - 欧拉函数: ACM/数学/数论/欧拉函数.md
        - 逆元: ACM/数学/数论/逆元.md
        - BSGS和扩展BSGS: ACM/数学/数论/BSGS.md
        - 扩展欧几里德和贝祖定理: ACM/数学/数论/扩欧.md
        - 中国剩余定理: ACM/数学/数论/crt.md
        - 积性函数与莫比乌斯反演: ACM/数学/数论/莫反.md
        - 例题: ACM/数学/数论/例题.md
      - 期望: ACM/数学/期望/期望.md
    - 动态规划:
      - 区间DP: ACM/动态规划/区间DP.md
      - 树形DP: ACM/动态规划/树形DP.md
  - PS: 
    - 基础知识入门: PS/base.md
    - 图像的基本编辑方法: PS/PS1.md
    - 选区与抠图: PS/PS2.md
    - 图像绘制: PS/PS3.md
    - 修复工具与图像润色工具: PS/PS4.md
    - 矢量工具与路径: PS/PS5.md
    - 文字的艺术: PS/PS6.md
    - 图层的基本操作: PS/PS7.md
    - 图层的高级操作: PS/PS8.md
    - 通道的应用: PS/PS9.md
    - 蒙版: PS/PS10.md
  - Web:
    - html: 
      - html基础标签: Web/html/html1.md
      - 文本标签: Web/html/html2.md
      - 图片: Web/html/html3.md
      - 音频和视频: Web/html/html4.md
      - 超链接: Web/html/html5.md
      - 表单: Web/html/html6.md
      - 列表: Web/html/html7.md
      - 表格: Web/html/html8.md
      - 语义标签: Web/html/html9.md
      - 特殊符号: Web/html/html10.md
    - CSS: 
      - 样式定义方式: Web/CSS/CSS1.md
      - 选择器: Web/CSS/CSS2.md
      - 颜色: Web/CSS/CSS3.md
      - 文本: Web/CSS/CSS4.md
      - 字体: Web/CSS/CSS5.md
      - 背景: Web/CSS/CSS6.md
      - 边框: Web/CSS/CSS7.md
      - 元素展示格式: Web/CSS/CSS8.md
      - 内边距与外边距: Web/CSS/CSS9.md
      - 盒子模型: Web/CSS/CSS10.md
      - 位置: Web/CSS/CSS11.md
      - 浮动: Web/CSS/CSS12.md
      - flex布局: Web/CSS/CSS13.md
      - 响应式布局: Web/CSS/CSS14.md
  - about:
    - 关于作者: 关于/作者.md
    - 关于算法竞赛: 关于/大学.md
    
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  # favicon: img/favicon.png
  icon:
    logo: material/library

  palette:
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: white
    accent: red
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: cyan
    accent: red
    toggle:
      icon: material/weather-night
      name: Switch to light mode

# copyright
copyright: Copyright &copy; 2022 <a href="#" target="_blank" rel="noopener noreferrer">方毓乔</a>

# extra
extra:
  search:
    language: 'jp'


# md extrc
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
    - 'js/mathjax.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  
extra_css:
  - css/mycss.css
  